variable "project_id" {
  description = "GCP project id"
  type = string
}

variable "region" {
  description = "GCP Region"
  type = string
}

variable "zone" {
  description = "GCP Zone"
  type = string
}

variable "gke_num_nodes" {
  default     = 1
  description = "number of gke nodes"
}

# serviceAccount:
variable "sa_email" {
  description = "Service account email"
  type = string
}

variable "privatecloud_cred" {
  description = "Credentials generated by the GCVE cloud creator"
  type = string
}

variable "tm_repo_path" {
  description = "Local path of github.com/test_infra"
  type = string
}